title: LLMonPy
author:
  name: Tom Burns
  email: public@llmonpy.ai
#theme: minima
remote_theme: jekyll/minima
skin: dark
social_links:
  - {platform: linkedin, user_url: https://www.linkedin.com/in/tombu }
